import type { Application, KnowledgeBase, ModelProfile } from "../../types";

interface Props { apps: Application[]; knowledgeBases: KnowledgeBase[]; llmModels: ModelProfile[]; selectedAppId: string; onCreate: () => void; onUse: (id: string) => void; onDelete: (id: string) => Promise<void>; onKnowledge: () => void; onModels: () => void; }
const modelLabel = (profile: ModelProfile): string => profile.model?.trim() || profile.name;
export function ApplicationView({ apps, knowledgeBases, llmModels, selectedAppId, onCreate, onUse, onDelete, onKnowledge, onModels }: Props) {
  const hasReady = knowledgeBases.some((item) => item.status === "ready");
  const canCreate = hasReady && llmModels.length > 0;
 return <section><div className="section-heading"><div><h2>Agent</h2><p>创建绑定知识库的对话 Agent。</p></div><div className="section-actions"><button className="primary-button" onClick={onCreate} type="button" disabled={!canCreate}>+ 新建 Agent</button></div></div>{apps.length ? <div className="app-card-grid">{apps.map((item) => { const kb = knowledgeBases.find((entry) => entry.id === item.knowledge_base_id); const llm = llmModels.find((entry) => entry.id === item.llm_model_id) || (!item.llm_model_id ? llmModels.find((entry) => entry.is_default) : undefined); return <article className="app-card" key={item.id}><div className="app-card-top"><div><h3>{item.name}</h3><p>{item.description || "未填写描述"}</p></div>{item.id === selectedAppId && <span className="tag ready">当前使用</span>}</div><div className="app-card-footer"><span>{kb?.name || "知识库已移除"}</span><span>{llm ? modelLabel(llm) : "LLM 配置已移除"}{!item.llm_model_id && llm ? " · 默认" : ""}</span></div><div className="section-actions" style={{ marginTop: 14 }}><button className="outline-button" onClick={() => onUse(item.id)} type="button">进入对话</button><button className="quiet-button danger-button" onClick={() => void onDelete(item.id)} type="button">删除 Agent</button></div></article>; })}</div> : <div className="empty-state"><div><div className="empty-state-mark" aria-hidden="true">⌘</div><h2>还没有 Agent</h2><p>{!hasReady ? "请先创建知识库并等待索引就绪，再创建 Agent。" : !llmModels.length ? "请先配置一个 LLM 模型，再创建 Agent。" : "选择知识库和 LLM 模型创建 Agent，之后即可开始对话。"}</p>{!hasReady ? <button className="outline-button" onClick={onKnowledge} type="button">去创建知识库</button> : !llmModels.length ? <button className="outline-button" onClick={onModels} type="button">去配置模型</button> : <button className="primary-button" onClick={onCreate} type="button">创建第一个 Agent</button>}</div></div>}</section>;
}
